name: ML Pipeline CI/CD

on:
  push:
    branches:
      - master  # Asegúrate de que esta sea la rama correcta en tu repositorio
  pull_request:
    branches:
      - master  # Asegúrate de que esta sea la rama correcta en tu repositorio

jobs:
  build:
    runs-on: ubuntu-latest  # Ejecutará el flujo de trabajo en un entorno Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Clona el repositorio para tener acceso al código

    - name: Set up Python
      uses: actions/setup-python@v2  # Configura la versión de Python
      with:
        python-version: '3.8'  # Versión de Python que deseas usar

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Actualiza pip
        pip install -r requirements.txt  # Instala las dependencias de tu archivo requirements.txt

    - name: Run Makefile install
      run: make install  # Ejecuta el comando `make install` para instalar dependencias adicionales si las hay

    - name: Run tests
      run: make test  # Ejecuta el comando `make test` para realizar pruebas (asegúrate de tener este paso configurado)

    - name: Train model
      run: make train  # Ejecuta el comando `make train` para entrenar el modelo

    - name: List mlruns directory  # Verifica que el modelo esté en la carpeta mlruns/
      run: ls -R mlruns/

    - name: Upload MLflow model as artifact
      uses: actions/upload-artifact@v1  # Cambié a la versión v1 de la acción
      with:
        name: model
        path: mlruns/
